<?php
require_once('header.phtml');
//include('Subscribe2.php');
//$sub = new Subscribe2();
//$dataSet = new Dataset();
//$display1 = $_SESSION['newVal'];
//$pageTitle = $_SESSION['pageTitle'];
//$newSetPointName = $_SESSION['newSetPoint'];

?>

<style>
    canvas{
        -moz-user-select: none;
        -webkit-user-select: none;
        -ms-user-select: none;
    }
    #chartjs-tooltip {
        opacity: 1;
        position: absolute;
        background: rgba(0, 0, 0, .7);
        color: white;
        border-radius: 3px;
        -webkit-transition: all .1s ease;
        transition: all .1s ease;
        pointer-events: none;
        -webkit-transform: translate(-50%, 0);
        transform: translate(-50%, 0);
    }

    .chartjs-tooltip-key {
        display: inline-block;
        width: 10px;
        height: 10px;
        margin-right: 10px;
    }
</style>

<script xmlns="http://www.w3.org/1999/html">
    setTimeout(function() { window.location=window.location;},30000);
</script>



<div>
    <nav class="navbar navbar-default">
            <div class="collapse navbar-collapse dropdown pull-right">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Select SetPoint
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <form id= "frmDrop" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">


                    <select class="dropdown-item" id="setpoint" name="setpointMenu" onchange="change()">
                        <?php for($x = 1; $x <= 8; $x++){
                            echo
                               '<option>setpoint' . $x .'</option>';
                        }
                        ?>
                    </select>

</div>
                <input type="submit" value="ok" class="btn btn-default">
                <script>
                    function change(){
                        document.getElementById("frmDrop").submit();
                        alert("new setpoint selected");
                       // window.location.reload();
                    }
                </script>
                </form>


            </div>

        <div class="pull-left">
            <form action="Csv.php" method="post">
                <input type="text" name="newSetPointName" placeholder="Name of new setpoint" <?php echo $_POST['newSetPointName']; ?>>
                <input type="submit" name="addSetPoint" value="Add" >

            </form>
        </div>

        </div>
    </nav>


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Display of </h4>
                        <h4 class="title"><?php echo $pageTitle ?></h4>
                        <p class="category">Short description of <?php echo $desc;?></p>

                    </div>
                    <div id="Hidden1" class="content">
                        <div class="content"></div>
                        <div class="GaugeMeter" data-style="Arch" data-theme="DarkBlue-LightBlue" data-stripe=2.5 data-percent =<?php echo $display1;?>>

                        </div>
                        <h1>  </h1>


                        <div class="footer">

                            <hr>
                            <div class="stats">
                                <i class="fa fa-clock-o"></i> Time when set
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Historical Data</h4>
                        <p class="category">Description of historical data</p>
                    </div>
                    <div class="content">

                        <div id="canvas-holder1" style="width:75%;">
                            <canvas id="chart" title="History" />
                        </div>

                        <hr>
                        <div class="stats">
                            <i class="fa fa-history"></i> Updated 2 minutes ago
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card ">
                <div class="header">

                    <h4 class="title"><?php echo $desc;?></h4>
                    <p class="category">description of <?php echo $desc;?></p>

                </div>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                    <div class="content">


                        <?php echo '<form action="setpoint.php" method="post">';
                        echo '<input type= "radio" name="option" value="ON">ON';
                        echo '<input type= "radio" name="option" value="OFF">OFF';
                        echo '<input type="submit" name="s" value="Go">';
                        echo '</form>' ;
                        ?>
                <?php
                       if (isset($_POST['s'])) {

                           if (isset($_POST['option'])) {


                               if ($_POST['option'] == 'ON') {


                                   echo
                                       '<input type= "number" placeholder="15°" name="newTemp2"' . $_POST['newTemp2'];
                                   echo '<a href="setpoint.php"> <input type="submit" name="set1" value="Submit Setpoint"></a>';
                               } else {

                                   echo " Set point is off";
                                   echo '<script> document.getElementById("Hidden1").style.visibility="hidden"; </script>;';

                               }
                           }
                       }
                        ?>
                    </div>
                </form>
                <div class="footer">
                    <div class="legend">
                        <i class="content"></i> Input type: Celsius
                        <i class="content text-danger"></i> Input Place: Room 1
                    </div>
                    <hr>
                    <div class="stats">
                        <i class="fa fa-check"></i> Something
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card ">
            <div class="header">
                <h4 class="title">Download</h4>
                <p class="category"><?php echo $desc;?> data</p>
            </div>
            <div class="content">
                <div class="table-full-width">
                    <form class="" action="Csv.php" method="post">

                        <label for="from">FROM</label>
                        <input placeholder="eg: 17-03-2016 20:00:00"  type="text" name="from"/>


                        <label for="to">TO</label>
                        <input placeholder="eg: 17-03-2016 23:00:00" type="text" name="to"/>

                        <input class="btn btn-default" type="submit" value="Generate File">
                    </form>

                    <?php

                    $dir    = 'temp';
                    $files = scandir($dir);

                    foreach($files as $f){
                        $info = new SplFileInfo($f);
                        $ext = $info->getExtension();

                        if($ext === 'csv'){
                            echo $file . "<a class='btn btn-success' href=download.php?files=" .$dir.'/'. urlencode($f) . ">Ready to download</a><br>";
                        }
                    }
                    ?>

                </div>

                <div class="footer">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-history"></i> Something
                    </div>
                </div>
            </div>
        </div>

    </div>
 </div>



<!--   Core JS Files   -->
<script src="assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="assets/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="/assets/js/jquery.AshAlom.gaugeMeter-2.0.0.min.js"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="assets/js/bootstrap-checkbox-radio-switch.js"></script>

<!--  Charts Plugin -->
<script src="assets/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="assets/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="assets/js/light-bootstrap-dashboard.js"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="assets/js/demo.js"></script>

<script type="text/javascript">

    $(".GaugeMeter").gaugeMeter();

</script>


<script src="assets/js/Chart.bundle.js"></script>
<script src="assets/js/utils.js"></script>


<script>
    Chart.defaults.global.pointHitDetectionRadius = 1;

    var customTooltips = function(tooltip) {
        // Tooltip Element
        var tooltipEl = document.getElementById('chartjs-tooltip');

        if (!tooltipEl) {
            tooltipEl = document.createElement('div');
            tooltipEl.id = 'chartjs-tooltip';
            tooltipEl.innerHTML = "<table></table>"
            document.body.appendChild(tooltipEl);
        }

        // Hide if no tooltip
        if (tooltip.opacity === 0) {
            tooltipEl.style.opacity = 0;
            return;
        }

        // Set caret Position
        tooltipEl.classList.remove('above', 'below', 'no-transform');
        if (tooltip.yAlign) {
            tooltipEl.classList.add(tooltip.yAlign);
        } else {
            tooltipEl.classList.add('no-transform');
        }

        function getBody(bodyItem) {
            return bodyItem.lines;
        }

        // Set Text
        if (tooltip.body) {
            var titleLines = tooltip.title || [];
            var bodyLines = tooltip.body.map(getBody);

            var innerHtml = '<thead>';

            titleLines.forEach(function(title) {
                innerHtml += '<tr><th>' + title + '</th></tr>';
            });
            innerHtml += '</thead><tbody>';

            bodyLines.forEach(function(body, i) {
                var colors = tooltip.labelColors[i];
                var style = 'background:' + colors.backgroundColor;
                style += '; border-color:' + colors.borderColor;
                style += '; border-width: 2px';
                var span = '<span class="chartjs-tooltip-key" style="' + style + '"></span>';
                innerHtml += '<tr><td>' + span + body + '</td></tr>';
            });
            innerHtml += '</tbody>';

            var tableRoot = tooltipEl.querySelector('table');
            tableRoot.innerHTML = innerHtml;
        }

        var position = this._chart.canvas.getBoundingClientRect();

        // Display, position, and set styles for font
        tooltipEl.style.opacity = 1;
        tooltipEl.style.left = position.left + tooltip.caretX + 'px';
        tooltipEl.style.top = position.top + tooltip.caretY + 'px';
        tooltipEl.style.fontFamily = tooltip._fontFamily;
        tooltipEl.style.fontSize = tooltip.fontSize;
        tooltipEl.style.fontStyle = tooltip._fontStyle;
        tooltipEl.style.padding = tooltip.yPadding + 'px ' + tooltip.xPadding + 'px';
    };

    var lineChartData = {
        labels: ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00","12:00", "13:00", "14:00", "15:00", "16:00", "17:00","18:00", "19:00", "20:00", "22:00", "23:00"],
        datasets: [{
            label: "Temperature",
            borderColor: window.chartColors.red,
            pointBackgroundColor: window.chartColors.red,
            fill: false,
            data: [

                23,
                24,
                20,
                23,
                23,
                24,
                26,
                27,
                17,
                15,
                19,
                15,
            ]
        }, {
            label: "Money Saved",
            borderColor: window.chartColors.blue,
            pointBackgroundColor: window.chartColors.blue,
            fill: false,
            data: [

            ]
        }]
    };

    window.onload = function() {
        var chartEl = document.getElementById("chart");
        window.myLine = new Chart(chartEl, {
            type: 'line',
            data: lineChartData,
            options: {
                title:{
                    display:true,
                    text:'2017 Setpoint History Chart'
                },
                tooltips: {
                    enabled: false,
                    mode: 'index',
                    position: 'nearest',
                    custom: customTooltips
                }
            }
        });
    };
</script>
