<?php require('Models/phpMQTT.php')?>

<?php
$mqtt = new phpMQTT("146.87.2.99", 1883, 60); //Change client name to something unique
if(!$mqtt->connect()){
    exit(1);

}

$topic = '';
$msg = '';
$topics['/wind_d'] = array("qos"=>0, "function"=>"procmsg");

$mqtt->subscribe($topics,0);
function procmsg($topic, $msg)
{

    echo "Msg Recieved: "."\nTopic:{$topic}\n$msg\n";
    //echo "Msg Recieved: " . date("r") ."\nTopic:{$topic}\n$msg\n";



}
for ($i = 0; $i < 4; $i++) {
    if ($mqtt->proc()) {

       procmsg($topic, $msg);


    }

}



$mqtt->close();



?>

<?php
$url1=$_SERVER['REQUEST_URI'];
header("Refresh: 1; URL=subscribe.php");
?>
