<?php require('Models/phpMQTT.php')?>

<?php
$mqtt = new phpMQTT("146.87.2.99", 1883, 60); //Change client name to something unique
if(!$mqtt->connect()){
    exit(1);

}

//$c = $_POST['c'];
$topics['/temp'] = array("qos"=>0, "function"=>"procmsg");

$mqtt->subscribe($topics,0);


while($mqtt->proc()) {



    function procmsg($topic, $msg)
    {

        echo "Msg Recieved: " . date("r") . "\nTopic:{$topic}\n$msg\n";

    }

}
$mqtt->close();



?>