<?php

?>;

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Remote heating system</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="assets/css/light-bootstrap-dashboard.css" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />

</head>
<body>


<div class="sidebar" data-color="azure" data-image="assets/img/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text">
                SPAT Team 6
            </a>
        </div>

        <ul class="nav">
            <li class="active">
                <a href="home.php">
                    <i class="pe-7s-graph"></i>
                    <p>Dashboard</p>
                </a>
            </li>

            <li>
                <a href="setpoint.php">
                    <i class="pe-7s-graph"></i>
                    <p>Setpoints</p>
                </a>
            </li>

            <li>
                <a href="airTemp.php">
                    <i class="pe-7s-graph"></i>
                    <p>Air Temperature</p>
                </a>
            </li>

            <li>
                <a href="rain.php">
                    <i class="pe-7s-graph"></i>
                    <p>Rain</p>
                </a>
            </li>

            <li>
                <a href="windSpeed.php">
                    <i class="pe-7s-graph"></i>
                    <p>Wind Speed</p>
                </a>
            </li>

            <li>
                <a href="windDirection.php">
                    <i class="pe-7s-graph"></i>
                    <p>Wind Direction</p>
                </a>
            </li>

            <li>
                <a href="solar.php">
                    <i class="pe-7s-graph"></i>
                    <p>Solar</p>
                </a>
            </li>

            <li>
                <a href="humidity.php">
                    <i class="pe-7s-graph"></i>
                    <p>Humidity</p>
                </a>
            </li>

            <li>
                <a href="airPressure.php">
                    <i class="pe-7s-graph"></i>
                    <p>Air Pressure</p>
                </a>
            </li>

            <li>
                <a href="savings.php">
                    <i class="pe-7s-graph"></i>
                    <p>Savings</p>
                </a>
            </li>

        </ul>
    </div>
</div>

<div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
        <div class="container-fluid">
            <div class="navbar-header">

                <a class="navbar-brand" href="#">Weather Station</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-left">

                    <li>
                        <a href="">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>


            </div>
        </div>
    </nav>
