<?php
require_once('header.phtml');
//include('../home.php');
?>

<div class="wrapper">
        <div class="content"> 
            <div class="container-fluid"> 
                <div class="row"> 
                    <div class="col-md-12"> 
                        <div class="card"> 
                            <div class="header"> 
                                <h4 class="title">Air Temperature</h4> 
                                <p class="category">Displaying the air temperature in Celsius</p> 
                            </div> 

                            <div class="content"> 
                                <!--START--> 
                                <div class="row"> 
                                    <div class="col-md-4"> 
                                        <div class="card-group"> 
                                            <div class="card-block"> 
                                                <div class="GaugeMeter" data-style="Arch" data-theme="DarkBlue-LightBlue" data-stripe=2.5 data-percent= "10">
                                                </div> 
                                            </div> 
                                        </div> 
                                    </div>
                                    <div class="col-md-4"> 
                                        <div class="card-group"> 
                                            <div class="card-block"> 
                                                <div class="GaugeMeter" data-style="Arch" data-theme="DarkBlue-LightBlue" data-stripe=2.5 data-percent="10">
                                                </div> 
                                            </div> 
                                        </div> 
                                    </div>  
                                </div> 

                            </div> 

                            <div class="footer"> 
                                <hr> 
                                <div class="stats"> 
                                    <i class="fa fa-clock-o"></i> Time when set <br> 
                                    <div class="content col-md-6"> 
                                        <p class="small text-justify">Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. 
                                            Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, 
                                            cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó </p> 
                                    </div>
                                    <div class="content col-md-6"> 
                                        <p class="small text-justify">Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. 
                                            Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, 
                                            cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó </p> 
                                    </div>
                                    <input type="submit" value="info" name="view" class="btn btn-default btn-sm pull-right">  
                                </div> 
                            </div>  
                        </div> 






                        <div class="row">

                            <div class="col-md-4">

                                <div class="card">

                                    <div class="header">

                                        <h4 class="title">Display of setpoint 1</h4>

                                        <p class="category">Short description of setpoint 1</p>

                                    </div>

                                    <div class="content">

                                        <div class="content"></div>


                                        <div class="footer">


                                            <hr>

                                            <div class="stats">

                                                <i class="fa fa-clock-o"></i> Time when set

                                            </div>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class="col-md-4">

                                <div class="card">

                                    <div class="header">

                                        <h4 class="title">Display of setpoint 1</h4>

                                        <p class="category">Short description of setpoint 1</p>

                                    </div>

                                    <div class="content">

                                        <div class="content"></div>


                                        <div class="footer">


                                            <hr>

                                            <div class="stats">

                                                <i class="fa fa-clock-o"></i> Time when set

                                            </div>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class="col-md-4">

                                <div class="card">

                                    <div class="header">

                                        <h4 class="title">Display of setpoint 1</h4>

                                        <p class="category">Short description of setpoint 1</p>

                                    </div>

                                    <div class="content">

                                        <div class="content"></div>


                                        <div class="footer">


                                            <hr>

                                            <div class="stats">

                                                <i class="fa fa-clock-o"></i> Time when set

                                            </div>

                                        </div>

                                    </div>

                                </div>











                            </div> 













                </div> 






            </div>  


        </div> 



</div>

</div>
    </div>


<?php require_once('footer.phtml'); ?>

<script src="assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="assets/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="/assets/js/jquery.AshAlom.gaugeMeter-2.0.0.min.js"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="assets/js/bootstrap-checkbox-radio-switch.js"></script>

<!--  Charts Plugin -->
<script src="assets/js/chartist.min.js"></script>

<script type="text/javascript">

    $(".GaugeMeter").gaugeMeter();

</script>


</html>

