<?php
require_once('header.phtml');
//include('Subscribe2.php');
//$sub = new Subscribe2();
//$dataSet = new Dataset();
//$display1 = $_SESSION['newVal'];
//$pageTitle = $_SESSION['pageTitle'];
//$newSetPointName = $_SESSION['newSetPoint'];

?>
<div>
    <nav class="navbar navbar-default">
            <div class="collapse navbar-collapse dropdown pull-right">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Select SetPoint
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">


                    <select class="dropdown-item" id="setpoint" name="setpoint">
                        <option selected="selected" value="setpoint1">Setpoint 1</option>
                        <option value="setpoint2">Setpoint 2</option>
                        <option value="setpoint3">Setpoint 3</option>
                        <option value="setpoint4">Setpoint 4</option>
                    </select>


                </form>
            </div>

            </div>

        <div class="pull-left">
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>">
                <input type="text" name="newSetPointName" placeholder="Name of new setpoint" <?php echo $_POST['newSetPointName']; ?>>
                <input type="submit" name="addSetPoint" value="Add" onClick="addOption()">

            </form>
        </div>

        </div>
    </nav>


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Display of setpoint 1</h4>
                        <h4 class="title"><?php echo $pageTitle ?></h4>
                        <p class="category">Short description of setpoint 1</p>
                    </div>
                    <div class="content">
                        <div class="content"></div>
                        <div class="GaugeMeter" data-style="Arch" data-theme="DarkBlue-LightBlue" data-stripe=2.5 data-percent =<?php echo $display1;?>>

                        </div>
                        <h1>  </h1>


                        <div class="footer">

                            <hr>
                            <div class="stats">
                                <i class="fa fa-clock-o"></i> Time when set
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Historical Data</h4>
                        <p class="category">Description of historical data</p>
                    </div>
                    <div class="content">

                        <table class="table table-bordered table-striped table-hover marginTable">
                            <thead>
                            <tr>

                                <th><h4 class="display-4">Id</h4></th><th><h4 class="display-4">Value in °C</h4></th><th><h4 class="display-4">Time</h4></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach((array)$view->dataset as $data){
                                echo



                                    '</td> <td class="col-md-8 col-sm-8 col-lg-8 text-left">'.$data->getId().
                                    '</td> <td >' . '<h6 class="lead">'.$data->getValue() .'</h6>'.
                                    '</td> <td >' . '<h6 class="lead">'.$data->getTime() .'</h6>'.
                                    '</tbody>';


                            } ?>
                        </table>

                        <hr>
                        <div class="stats">
                            <i class="fa fa-history"></i> Updated 2 minutes ago
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card ">
                <div class="header">
                    <h4 class="title">Setpoint 1</h4>
                    <p class="category">description of setpoint 1</p>
                </div>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                    <div class="content">
                        <input type="number" placeholder="15°" name="newTemp1" <?php echo $_POST['newTemp1']; ?> >
                        <input type="submit" name="set1">
                </form>
                <div class="footer">
                    <div class="legend">
                        <i class="content"></i> Input type: Celsius
                        <i class="content text-danger"></i> Input Place: Room 1
                    </div>
                    <hr>
                    <div class="stats">
                        <i class="fa fa-check"></i> Something
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card ">
            <div class="header">
                <h4 class="title">Download</h4>
                <p class="category">setpoint 1 data</p>
            </div>
            <div class="content">
                <div class="table-full-width">

                    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                        <div class="content">
                            <input type="submit" name="downloadBtn" value="Download">
                        </div>
                    </form>




                </div>

                <div class="footer">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-history"></i> Something
                    </div>
                </div>
            </div>
        </div>

    </div>
 </div>



<!--   Core JS Files   -->
<script src="assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="assets/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="/assets/js/jquery.AshAlom.gaugeMeter-2.0.0.min.js"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="assets/js/bootstrap-checkbox-radio-switch.js"></script>

<!--  Charts Plugin -->
<script src="assets/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="assets/js/bootstrap-notify.js"></script>

<script type="text/javascript">

    $(".GaugeMeter").gaugeMeter();

    function addOption(){
        var select = document.getElementById('setpoint');
        select.options[select.options.length] = new Option('<?php echo $newSetPointName ?>', '<?php echo $newSetPointName ?>');
    }

</script>





